name: Calix
version: 1.0
description: A simple plug-in for managing conflicts between players, with a simple enemy and war system.
author: nickelulz
website: https://github.com/nickelulz/calix-addons
main: xyz.nickelulz.calix.Calix
api-version: '1.21.5'
